#!/bin/bash -l
#PBS -N lstr_test
#PBS -l select=1:ncpus=4:ngpus=1:mem=64GB
#PBS -l walltime=00:30:00
#PBS -j oe

cd ~/long-short-term-transformer_forked

module load Miniconda3
conda activate lstr

export PYTHONPATH=$PYTHONPATH:$(pwd)/src

python tools/test_net.py \
    --config_file configs/THUMOS/LSTR/lstr_long_512_work_8_kinetics_1x.yaml \
    --gpu 0 \
    MODEL.CHECKPOINT checkpoints/THUMOS/LSTR/lstr_long_512_work_8_kinetics_1x/epoch-18.pth

