#!/bin/bash -l
#PBS -N segment_based
#PBS -l select=1:ncpus=4:ngpus=1:mem=32GB
#PBS -l walltime=24:00:00
#PBS -m abe
#PBS -M n11429984@qut.edu.au
#PBS -j oe
#PBS -q gpu_batch_exec
cd ~/long-short-term-transformer_forked

module load Miniconda3
conda activate lstr

export PYTHONPATH=$PYTHONPATH:$(pwd)/src

python tools/train_net.py \
    --config_file configs/THUMOS/LSTR/lstr_long_512_work_8_kinetics_1x.yaml \
    --gpu 0
